### ISSUE TITLE
Can't browse lower than artist

### ISSUE THREAD

**Issue by stooj** [xsteadfastx/mopidy-emby#6]
Using nmpcpp or a web browser, I can see a list of artists and albums.

However, I can't see lower than that.

```
DEBUG    2017-10-31 21:41:35,745 [9124:EmbyBackend-9] mopidy_emby.library
  Get Emby track list
DEBUG    2017-10-31 21:41:35,797 [9124:EmbyBackend-9] mopidy_emby.remote
  {u'Items': [{u'UserData': {u'PlayCount': 0, u'Key': u'MusicAlbum-MusicBrainzReleaseGroup-f722b0db-3035-3b4b-b499-57e42d4219c7', u'PlaybackPositionTicks': 0, u'IsFavorite': False, u'Played': False}, u'LocationType': u'FileSystem', u'Name': u'Greatest Hits', u'ImageTags': {u'Primary': u'2cce70436672bdafdc2c590fc7162da6'}, u'ArtistItems': [{u'Name': u'Bruce Springsteen', u'Id': u'b1eb5aee23cb07c0cc8dbfab05bed0ab'}], u'AlbumArtists': [{u'Name': u'Bruce Springsteen', u'Id': u'b1eb5aee23cb07c0cc8dbfab05bed0ab'}], u'IsFolder': True, u'ParentLogoImageTag': u'24f2486e1a66da0a581908d3dd06cbc6', u'ParentLogoItemId': u'b1eb5aee23cb07c0cc8dbfab05bed0ab', u'ParentBackdropItemId': u'b1eb5aee23cb07c0cc8dbfab05bed0ab', u'PremiereDate': u'1995-02-28T00:00:00.0000000Z', u'AlbumArtist': u'Bruce Springsteen', u'ProductionYear': 1995, u'RunTimeTicks': 46084730880, u'Artists': [u'Bruce Springsteen'], u'ParentBackdropImageTags': [u'f1eea8cfbf0bae199903c49235c3fce9'], u'ServerId': u'2cf01991076741bcb5b757a90f18a264', u'Type': u'MusicAlbum', u'Id': u'c7b06cf1b95e8f961b530d368bc94b84', u'BackdropImageTags': []}], u'TotalRecordCount': 1}
ERROR    2017-10-31 21:41:35,799 [9124:Core-10] mopidy.core.library
  EmbyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_emby/library.py", line 39, in browse
    return self.backend.remote.get_tracks(album_id)
  File "/usr/lib/python2.7/site-packages/mopidy_emby/remote.py", line 222, in get_tracks
    key=lambda k: k['IndexNumber']
  File "/usr/lib/python2.7/site-packages/mopidy_emby/remote.py", line 222, in <lambda>
    key=lambda k: k['IndexNumber']
KeyError: u'IndexNumber'
```

 Is this because my music nested an extra directory deep?

eg:

```
.
├── audiobooks
│   └── unabridged
│       ├── Terry Pratchett
│       └── Terry Pratchett read by Stephen Briggs
└── music
    ├── Bruce Springsteen
    │   └── Greatest Hits
    ├── CCP Games
    │   ├── EVE Online - Soundtrack
    │   └── EVE Online Trailer Music
    ├── Compilations
    │   ├── Natural Born Killers
        └── Wonder Boys
```

**Comment by xsteadfastx** [comment]
can you run mopidy with `mopidy -vvv`? like this i can see all api calls.

**Comment by xsteadfastx** [comment]
and what directory is declared as music directory?

**Comment by xsteadfastx** [comment]
i checked the code... yes its the problem. its a hirachy... artist -> album -> track and this breaks with your order. the emby api uses a endpoint that uses a parent id and gets all child items. the problem is that their api docs are kinda broken and i would love to find a way to search for music artists or tracks instead of just child items of a directory.

**Comment by stooj** [comment]
Sorry I was away for a few days...

Here's a triple-verbose log:

[mopidy.log](https://github.com/xsteadfastx/mopidy-emby/files/1446204/mopidy.log)

> and what directory is declared as music directory?

The top directory (`.` in that tree output) is declared as the music directory according to emby. It's called `audio`.

**Comment by xsteadfastx** [comment]
ok... i see where the problem is. i will check the emby api again if i find a other way to get albums and artists.. and not through directory hirachy. too bad the api documenary for emby is so broken.

**Comment by xsteadfastx** [comment]
ok... i see where the problem is. i will check the emby api again if i find a other way to get albums and artists.. and not through directory hirachy. too bad the api documenary for emby is so broken.

**Comment by stooj** [comment]
I have rearranged my directory hierarchy to work around the issue anyway.

Thanks for the awesome plugin :D

**Comment by xsteadfastx** [comment]
On Mo, 07. Mai 18:26, Stoo Johnston wrote:
> I have rearranged my directory hierarchy to work around the issue anyway.

i wish i would have more time. for some time the api browser of emby is
so broken that i couldnt dive more into the api that i dont have to
browse directories... i should look for audio artists -> audio albums ->
audio tracks and not the directories itself. i remember that i did this
at the beginning but had to change it because of a api problem.
